# Generated by Django 4.0.5 on 2022-06-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_api', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user', max_length=200)),
                ('usnername', models.CharField(max_length=200, unique=True)),
                ('email', models.CharField(max_length=75, unique=True)),
                ('password', models.CharField(max_length=1000)),
                ('hasRead', models.ManyToManyField(related_name='books_read', to='books_api.book')),
                ('isReading', models.ManyToManyField(related_name='books_reading', to='books_api.book')),
                ('toRead', models.ManyToManyField(related_name='books_wantToRead', to='books_api.book')),
            ],
        ),
    ]
