# Generated by Django 4.0.5 on 2022-06-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='usnername',
            new_name='username',
        ),
    ]
