# Generated by Django 4.0.5 on 2022-06-24 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_api', '0001_initial'),
        ('books_api', '0002_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_api.useraccount')),
                ('review_for_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books_api.book')),
            ],
        ),
    ]
