# Generated by Django 4.0.5 on 2022-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.TextField(null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('author_name', models.CharField(max_length=200, null=True)),
                ('genre', models.CharField(max_length=200, null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('isbn', models.CharField(max_length=128, null=True)),
                ('rating', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user_id', models.IntegerField(null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('book_id', models.IntegerField(null=True)),
            ],
        ),
    ]
